version: '3.2'

networks:
  enovateurs-network:
    driver: bridge
services:
  enovateurs-mailhog:
    image: mailhog/mailhog:v1.0.0
    networks:
      - enovateurs-network
    ports:
      - 8025:8025

  enovateurs-web:
    image: php:7.2-apache-stretch
    networks:
      - enovateurs-network
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./www/
        target: /var/www/html

  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - type: bind
        source: ./www/
        target: /var/www/html
    working_dir: /var/www/html